### PR TITLE
New function best_fit_thumbnail()

### PR DESCRIPTION
**Pull request by m-hume**
Creates thumbnails by resizing then cropping the image if its "square" enough else it resizes and gives it a background

### CODE REVIEW

**Comment by claviska** [comment]
Hi, thanks for the PR. I saw this in the comments:

> Creates thumbnails by resizing then cropping the image if its "square" enough else it resizes and gives it a background

Could you explain exactly how this method is intended to work? The name doesn't seem to be intuitive (i.e. I don't know what it does by reading it). We try to keep things as simple as possible, so just trying to identitfy if this is something that would be commonly used.

Also, is there a way to easily achieve the same effect by using exsting methods?

**Comment by m-hume** [comment]
Had forgotten i'd even made the pull request.
Basically its a thumbnail function for when you have no idea how square an image will be
when the image is reasonably square it crops the image to square
when the image ratio (height/width) is either very big or very small, it will reduce the image size to fit a square and pad the missing image with the given color
For instance making a thumbnail of a shovel doesn't just crop the image to the middle part of the handle, you get the full image with a filled color background.

**Comment by mikedidomizio** [comment]
Probably would be a good idea to add an example image and maybe add an example of it working in example/index.php in your pull request

**Comment by claviska** [comment]
This can be accomplished with a couple lines using existing methods so I'd prefer to keep the API slim :)

**Pull request closed without merging**
