### PR TITLE
Cleaner code for 'overlay()'

### PR DESCRIPTION
**Pull request by maPer77**
No changes in functionality, just cleaner code.

### CODE REVIEW

**Comment by maPer77** [comment]
The code takes the available space, initially sets X and Y as the default center, then only changes X or Y depending on whether left | right and top | bottom were set.
This eliminates code repetition.


// Get available space 
```
$spaceX = $this->getWidth() - $overlay->getWidth();
$spaceY = $this->getHeight() - $overlay->getHeight();
```

// Set default center
```
$x = ($spaceX / 2) + ($calcuateOffsetFromEdge ? 0 : $xOffset);
$y = ($spaceY / 2) + ($calcuateOffsetFromEdge ? 0 : $yOffset);

```
// Determine if top|bottom
```
if (strpos($anchor, 'top') !== false) {
  $y = $yOffset;
} elseif (strpos($anchor, 'bottom') !== false) {
  $y = $spaceY + ($calcuateOffsetFromEdge ? -$yOffset : $yOffset);
}
```

// Determine if left|right
```
if (strpos($anchor, 'left') !== false) {
  $x = $xOffset;
} elseif (strpos($anchor, 'right') !== false) {
  $x = $spaceX + ($calcuateOffsetFromEdge ? -$xOffset : $xOffset);
}
```

**Review by claviska — APPROVED** [review]

**Comment by claviska** [comment]
Nice approach to optimizing this! Looks like there's a merge conflict, but aside from that this looks great.

**Comment by maPer77** [comment]
I don't know why this conflict occurred, how do I resolve it?

**Comment by claviska** [comment]
No worries, it was just one block so I took care of it. Mind double checking that everything still looks good in master now?

Thanks!

**Comment by maPer77** [comment]
Yes, it was a "switch" code block ...
Everything is ok now.

**Comment by maPer77** [comment]
I'm optimizing the "text" function, fixing problem #212 , there is a "switch" block that can also be optimized, I want to do this after fixing the problem.
I believe it will also improve the problem #165 
I'm also implementing "calcuateOffsetFromEdge" in text(), in the same way used in overlay().
I must send this soon.

**Pull request merged**
