### PR TITLE
changed from iteration through each pixel to imagefilter with alphaval

### PR DESCRIPTION
**Pull request by rsiemoneit**
Hi, there is a big performance issue in `imageCopyMergeAlpha`. Iterating through every pixel of the overlay is very slow. I tried to put an overlay (1748x1328) onto my image (5184x3456) and `imageCopyMergeAlpha` needs 4.642.688 iterations to set the opacity. This took 7 - 7.5 seconds. I tried another approach with `imagefilter`, and it seems to be a bit faster. Give it a try. ;)

### CODE REVIEW

**Comment by claviska** [comment]
Correct, performance isn't great on that at the moment. Your solution does seem to work — I'm testing it with various images with and without transparency.

Quick question: where did you discover [this technique](https://github.com/claviska/SimpleImage/pull/168/commits/1d77b084fad0cbaad83d10cebe52ae4c81a1afca#diff-88dd2efe0e7f544f22fd56eab1ebad03R444)? Can you explain how it works?

**Comment by rsiemoneit** [comment]
Basicly, the idea came from a thread on stackoverflow. 
http://stackoverflow.com/questions/14468405/change-the-opacity-of-an-image-in-php

It maybe depends on PHP or GD version.
My project runs with PHP 5.5.26 and GD 2.1.0.

**Comment by claviska** [comment]
This is passing all my tests, but some of the lines aren't necessary.

- Line 441 has no affect since we're never generating an image from that resource.
- Line 447 has no affect since alpha blending is `true` by default for the internal true color image.
- Line 448 has no affect since we're done processing this image.
- Line 483 and 484 has no affect on `imagecopy` and aren't necessary.

I really want to give you credit for this excellent contribution, so I'll share what's passing all my tests and what I'd like to accept. I also tried to make the comments explain the behavior more clearly. 😀

```php
//
// Same as PHP's imagecopymerge, but works with transparent images. Used internally for overlay.
//
private static function imageCopyMergeAlpha($dstIm, $srcIm, $dstX, $dstY, $srcX, $srcY, $srcW, $srcH, $pct) {
  // Are we merging with transparency?
  if($pct < 100) {
    // Disable alpha blending and "colorize" the image using a transparent color
    imagealphablending($srcIm, false);
    imagefilter($srcIm, IMG_FILTER_COLORIZE, 0, 0, 0, 127 * ((100 - $pct) / 100));
  }

  imagecopy($dstIm, $srcIm, $dstX, $dstY, $srcX, $srcY, $srcW, $srcH);

  return true;
}
```

This is an awesome performance boost!

**Comment by rsiemoneit** [comment]
Yes, it is. I love your work and this performance boost makes this class indispensable for me. Good work, keep on.

**Comment by claviska** [comment]
Thanks. If you want to update the PR I'll accept. If not, let me know and I'll be happy to credit you in the description.

**Pull request merged**
