### PR TITLE
PHP 8.2: fix deprecation warning

### PR DESCRIPTION
**Pull request by distantnative**
Fixes https://github.com/claviska/SimpleImage/issues/305

### CODE REVIEW

**Review by claviska — APPROVED** [review]

**Comment by distantnative** [comment]
@claviska do you already know when you will release a new version incl. this fix?

**Comment by claviska** [comment]
Just published 3.7.1. Thanks again!

**Comment by distantnative** [comment]
@claviska 3.7.1 doesn't seem to include this fix unfortunately

**Comment by claviska** [comment]
Sorry, I messed up when creating the tag. 3.7.2 has been released and includes this fix. https://github.com/claviska/SimpleImage/releases/tag/3.7.2

**Pull request merged**
