### PR TITLE
'Orientation' index check.

### PR DESCRIPTION
**Pull request by kalimba**
if the index doesn't exist, a warning was throwing a warning.

### CODE REVIEW

**Comment by kalimba** [comment]
Hi,
It was a notice. I fixed as you write. 

I also added remote url support. I'm going to add "error image" support next pull request. I think if the image doesn't exist or any error occure, an error image would be displayed with  same requested size. I'm going to use this library creating a thumbnail and the created image is going to pass via cdn. Example: when i request like `http://www.example.com/sample.php?w=50&h=50` sample.php logic will be `$simple_thumbnailer->thumbnail($_GET['w'], $_GET['h'])->output('jpeg');`

Thanks.

**Comment by kalimba** [comment]
As far as see the library doesn't need any additional method to show an alternative error image.

I'm going to use like this.

```
$w = 1500;
$h = 500;

try{
    $simple_thumbnailer = new abeautifulsite\SimpleImage($image_file);
    $simple_thumbnailer->thumbnail($w, $h)->output();
}catch (Exception $e)
{
    $simple_thumbnailer = new abeautifulsite\SimpleImage(null, $w, $h, '#FFFFFF');
    $simple_thumbnailer->overlay('image_not_found.png')->output('jpg');
}
```

**Comment by kalimba** [comment]
Allowed domain list example.


```
$image_file = "http://subdomain.example.com/imagefile.jpg";
$w = 500;
$h = 500;

$SIMPLE_IMAGE_ALLOWED_DOMAINS = [
    'example.com'
];

try{
    $simple_thumbnailer = new abeautifulsite\SimpleImage($image_file);
    $simple_thumbnailer->thumbnail($w, $h)->output();
} catch (Exception $e) {
    $simple_thumbnailer = new abeautifulsite\SimpleImage(null, $w, $h, '#FFFFFF');
    $simple_thumbnailer->overlay('image_not_found.png')->output('jpg');
}
```

**Comment by claviska** [comment]
I don't think we should incorporate fetching images directly into the library. This can be done easily using fopen wrappers or PHP's cURL extension and neither are available universally. Furthermore, there are other protocols such as FTP and SFTP that we'd be leaving out, and adding those just feels like bloat.

I'd recommend using your own function to do the fetch and have it return a SimpleImage, then process it as usual.

**Pull request closed without merging**
