### PR TITLE
Ability to create thumbnails specifying the focal point

### PR DESCRIPTION
**Pull request by rasteiner**
This lets us use things like `$img->thumbnail($w, $h, 'top right')` instead of forcing us to use the currently implied `center`.

### CODE REVIEW

**Comment by jenstornell** [comment]
+1

**Comment by claviska** [comment]
This is great. Only one suggestion which I commented above. Otherwise a solid and helpful PR. :100:

**Comment by adaniello** [comment]
:+1: 
simply great

**Comment by rasteiner** [comment]
Oh, didn't think about that. Iv'e added a strtolower there.

**Pull request merged**
