### PR TITLE
Add BMP support

### LINKED ISSUE #171: Add support for bitmap (BMP) images
```PHP

array(1) { ["path"]=> string(89) "public/media/upload-files/2017/02/strawberries.bmp" }
E_ERROR [#1]: Uncaught Exception: Unsupported image: public/media/upload-files/2017/02/strawberries.bmp in vendor/claviska/simpleimage/src/claviska/SimpleImage.php:159 Stack trace: #0 vendor/claviska/simpleimage/src/claviska/SimpleImage.php(57): claviska\SimpleImage->fromFile('/var/www/vhosts...') #1/library/cms39_media.php(647): claviska\SimpleImage->__construct('/var/www/vhosts...') #2 /library/cms39_media.php(121): resizePhoto(Array) #3 /library/cms39_template.php(332): processImage('2017/02/strawbe...', Array) #4 /library/plugin.php(202): meta_og_image('') #5 /library/cms39_template.php(350): apply_filters('og_image', '') #6 /public/themes/default/header.php(25): meta_og_data() # in vendor/claviska/simpleimage/src/claviska/SimpleImage.php:159

```

here is the bmp file https://we.tl/4j5vpzud3A

### PR DESCRIPTION
**Pull request by Grayda**
Adds in BMP support that would resolve #171 

Tested by loading a BMP, resizing it and then saving it back as a BMP.

Obviously requires PHP 7+

### CODE REVIEW

**Comment by claviska** [comment]
Awesome, thanks!

Curious on the mime types. I figured it would be `image/bmp` but noticed you used a couple proprietary ones in addition. I got to googling and found [this](https://filext.com/file-extension/BMP). 😮

```
image/bmp, image/x-bmp, image/x-bitmap, image/x-xbitmap, image/x-win-bitmap, image/x-windows-bmp, image/ms-bmp, image/x-ms-bmp, application/bmp, application/x-bmp, application/x-win-bitmap
```

Are any/all of these applicable? Just wondering why you chose those two, or if you found something in the GD docs that explains why those should be used.

**Comment by johnabela** [comment]
Yeah, the [image_type_to_mime_type()](https://www.php.net/manual/en/function.image-type-to-mime-type.php) function has a returned value of `image/bmp` and the BMP [wikipedia page](https://en.wikipedia.org/wiki/BMP_file_format) lists both `image/bmp` and `image/x-bmp` while both [ietf.org](https://tools.ietf.org/html/rfc7903#section-4) and [iana.org](https://www.iana.org/assignments/media-types/image/bmp) indicates the only subtype is `image/bmp`.

**Comment by claviska** [comment]
This probably depends on the OS. I quickly found at least [one instance](https://stackoverflow.com/questions/2100875/unable-to-create-gd-image-resource-from-bmp-with-mime-type-image-x-ms-bmp-in-p) where `getimagesize()` returned `image/x-ms-bmp`. Not sure which ones are actually in use, though, or which ones should be included.

**Comment by Grayda** [comment]
> This probably depends on the OS. I quickly found at least [one instance](https://stackoverflow.com/questions/2100875/unable-to-create-gd-image-resource-from-bmp-with-mime-type-image-x-ms-bmp-in-p) where `getimagesize()` returned `image/x-ms-bmp`. Not sure which ones are actually in use, though, or which ones should be included.

I created a BMP in mspaint and then tried to load that through `imagecreatefrombmp` and `x-ms-bmp` and that was the type returned, so that's why I added `x-ms-bmp`. I then googled "BMP MIME type" and saw `image/x-windows-bmp` so I added that too.

No harm in adding the other types if PHP supports them, right? That is, if they're all different MIME types for the same base format..

**Comment by johnabela** [comment]
> No harm in adding the other types if PHP supports them, right?

Agreed.

Just out of curiosity, what Imagetype Constant do you get if you process the mspaint image that you made through [exif_imagetype()](https://www.php.net/manual/en/function.exif-imagetype.php) ??

Hopefully it returns type 6 _(IMAGETYPE_BMP)_ but just thought I would ask to see / make sure.

Hmm, might be a good idea to test it on both the original image and the one made by `imagecreatefrombmp()`, to see if it returns different results.

**Comment by Grayda** [comment]
Both the Windows BMP and the one converted using `imagecreatefrombmp()` return `int(6)`, which is `IMAGETYPE_BMP`

These were both tested on Windows 10 (Version 1709) with PHP 7.2.0

I just had a look at that fileext site, and they list a whole bunch of different MIME types for jpeg, including `image/x-xbitmap` (??), so rather than going down a rabbit's hole of MIME types for BMP and other types, I'd personally be inclined to leave the BMP MIME types as they are in my PR (given that they're the most common), and any new ones can be added via a PR

**Comment by claviska** [comment]
> I'd personally be inclined to leave the BMP MIME types as they are in my PR (given that they're the most common), and any new ones can be added via a PR

Agreed. Thanks for the solid PR!

**Pull request merged**
