### PR TITLE
Issue 117

### PR DESCRIPTION
**Pull request by jwadhams**
I also got burned by Issue #117 so I figured I'd just contribute a tiny patch.

I love the library, it's a real delight to use.

### CODE REVIEW

**Comment by claviska** [comment]
Happy to accept. I know it isn't the PHP way, but would you mind updated to two spaces instead of four per `.editorconfig`?

**Comment by jwadhams** [comment]
Sorry, didn't notice! Turns out Atom doesn't watch .editorconfig by default. 😳  Updated.

**Comment by claviska** [comment]
Nope, it doesn't, but there is [a plugin](https://github.com/sindresorhus/atom-editorconfig) at least 👍

Thanks for submitting!

**Comment by jwadhams** [comment]
Thanks! Do you mind giving it a tag so I can force the new version in Composer?

**Comment by claviska** [comment]
https://github.com/claviska/SimpleImage/releases/tag/3.3.2

**Pull request merged**
