### PR TITLE
Adds $borderOffset parameter to overlay ().

### PR DESCRIPTION
**Pull request by maPer77**
Calculates the offset for the image edges.

**$borderOffset false**
`overlay('watermark.png', 'bottom right', 1, 20, 20, false)`

borderOffset-false (Personalizado)

**$borderOffset true**
`overlay('watermark.png', 'bottom right', 1, 20, 20, true)`

borderOffset-true (Personalizado)

### CODE REVIEW

**Comment by maPer77** [comment]
The overlay code can be done in a cleaner way, I kept it that way to make it easier to see the changes ...
Then I send another suggestion for this code.

**Comment by claviska** [comment]
I'm not sure I understand what this is intended to do, but wouldn't this achieve the same effect?

```php
overlay('watermark.png', 'bottom right', 1, 0, 0)
```

**Comment by maPer77** [comment]
No, if using offset 0 the image will be glued to the edge ... the goal is to have a space between the edge and the watermark image

**Comment by maPer77** [comment]
`overlay('watermark.png', 'bottom right', 1, 0, 0)`
borderOffset-0

**Comment by claviska** [comment]
Apologies if I'm not understanding your intent here, but I don't think it will be obvious to other users either. What is the `$borderOffset` argument supposed to do, and why is it a boolean instead of a pixel value?

> the goal is to have a space between the edge and the watermark image

Can you not do this with the [`$xOffset` and `$yOffset` arguments](https://github.com/claviska/SimpleImage#overlayoverlay-anchor-opacity-xoffset-yoffset)?

**Comment by maPer77** [comment]
$ borderOffset is boolean because it only serves to indicate how the offset will be applied ...
As offset pattern is applied to the top and left of "watermark.jpg" this causes "watermark" to be out of the image if I use "bottom right" as in the example I posted in the first message ...

**Comment by maPer77** [comment]
_Can you not do this with the existing $xOffset and $yOffset arguments?_

yes, I can use it, but for that I have to use negative value, for example:
`overlay('watermark.png', 'bottom right', 1, -20, -20)`

With $ borderOffset true it looks like this:
`overlay('watermark.png', 'bottom right', 1, 20, 20, false)`

**Comment by maPer77** [comment]
How the offset works today, I must check which position to set the offset value correctly ...
sublime_text_WAa861Ex5c

with $ borderOffset true, I simply do this:
`overlay('watermark.png', 'bottom right', 1, 10, 10, true)`

**Comment by maPer77** [comment]
Did you understand what i meant ?

**Comment by claviska** [comment]
OK, thanks for explaining what you meant — it wasn't obvious that this was purely for convenience and I was pretty sure it could already be done with the existing parameters. The change makes more sense now. 😄 

I'm OK with adding it, but I'd suggest changing the name to `$calcuateOffsetFromEdge`. The current name `$borderOffset` isn't intuitive because the two preceding arguments are `$xOffset` and `$yOffset` which accept an integer. (That threw me off a bit too.)

The only other thing that needs to be done is to [update the docs](https://github.com/claviska/SimpleImage/blob/master/README.md#overlayoverlay-anchor-opacity-xoffset-yoffset) to describe the new argument. It's probably worth pointing out that `$xOffset` and `$yOffset` have no effect when `center` is used as an anchor.

**Comment by maPer77** [comment]
I don't know if the standard way of calculating the offset is useful for someone, speaking for me I don't see any use.
Could we not eliminate the standard form of calculation and use only this new form of calculation?

**Comment by claviska** [comment]
Your approach is more convenient, but modifying the default would be a breaking change so it would need to wait for 4.0. Since the library is fairly mature, I don't have any plans for 4.0 on the roadmap, but if that time comes I'd definitely like to revisit it.

**Pull request merged**
