### PR TITLE
Remove warning message

### PR DESCRIPTION
**Pull request by RahulKumarSaini**
Strict standards: Only variables should be passed by reference

### CODE REVIEW

**Comment by claviska** [comment]
Where are you getting the warning message? What PHP version?

Happy to accept but can we fix the indentation first?

**Comment by RahulKumarSaini** [comment]
I am getting warning message in PHP 5.5.12 and I have fix the indentation.

**Comment by claviska** [comment]
Sorry to nitpick, but your IDE is configured to use tabs but the source file uses spaces. It looks correct visually, but I caught it in the preview.

I'm still not sure why nobody else is seeing this warning, though. What code are you using to produce it?

I realize this appears to be a simple fix, but I want to understand _why_ this PR is necessary before accepting it. The docs for `imagettftext`(http://php.net/manual/en/function.imagettftext.php) don't mention anything about passing arguments by reference, and this method is used frequently and hasn't been modified recently.

Please post some sample code :)

**Comment by RahulKumarSaini** [comment]
I just run the sample code that i downloaded from git and then i receive this message . I am using wamp server with php 5.5.12  
screenshot-localhost 8080 2016-08-25 11-30-52

**Comment by claviska** [comment]
Ah, it's a notice. [This is relevant.](http://stackoverflow.com/questions/1248952/php-5-disable-strict-standards-error)

I don't bother with PHP notices, only warnings and errors 🙂

**Pull request closed without merging**
