### PR TITLE
Refactored output and save method

### PR DESCRIPTION
**Pull request by alexxandar**
I've noticed that output, output_base64 and save methods are using a lot of the same code. To avoid code repetition and make the future changes easier I've created a new method called _generate_. 
This method stores the image data and image mime type into class properties so they can be later used by methods output, output_base64 and save.

### CODE REVIEW

**Comment by claviska** [comment]
Good idea. Give me some time to review this more thoroughly and let others take a look. I don't see any obvious breaking changes, but other eyes might see something worth discussing :)

Care to also take a look, @nazar-pc?

**Comment by nazar-pc** [comment]
This is a change that should have been made a long time ago :+1: 

The only thing I do not really like is storing `$this->mimetype` and `$this->imagestring`, I'd rather `return [$mimetype, $imagestring]` from `::generate()`.

Currently it returns `$this`, but it is not used and anyway function is protected, so for me returning values directly and do not store something long-term in properties is better approach.

So instead of:
```php
$this->generate( $format, $quality );
return 'data:'.$this->mimetype.';base64,'.base64_encode($this->imagestring);
```
will be
```php
list( $mimetype, $imagestring ) = $this->generate( $format, $quality );
return "data:$mimetype;base64,".base64_encode($imagestring);
```

Looks more explicit, what you think?

**Comment by claviska** [comment]
Agreed. There's no functional reason to store it and subsequent calls to `generate()` will overwrite it. There may be use cases where a method needs to call `generate()` more than once and retain that data.

**Comment by alexxandar** [comment]
Agreed as well, only reason I did it was so that it would return $this, but as you said it's protected so no need for chaining.

**Comment by claviska** [comment]
I'd love to accept this and give you credit for the PR. If you'd like to make that change, we'll get it into SimpleImage this week. 👍

**Comment by alexxandar** [comment]
Changes made. Thanks for the reminder.

**Comment by claviska** [comment]
Beautiful work, thanks!

**Pull request merged**
