### PR TITLE
add get_raw function

### PR DESCRIPTION
**Pull request by lanaguanifw**
Added get_raw method for get the binary data of image.

### CODE REVIEW

**Comment by claviska** [comment]
Have you looked into the `output()` method? It's pretty much identical except it outputs to stdout. You could wrap your output buffering around that if you need to capture it as a string.

If that's not suitable, I'd prefer to add an output type flag to `output()` instead of adding a new method. Less duplication of code, easier to maintain :)

**Comment by lanaguanifw** [comment]
The flag is a solution too. Not necessarily the images are displayed or saved to a file, sometimes stored in a DB for example.

**Comment by lanaguanifw** [comment]
The fact is that we are looking for a simple utility as Simpleimage for a framework we are creating. In most cases required to obtain the raw binary data of image, is there a possibility that you incorporate a method to obtain the raw data? we can help...

**Comment by claviska** [comment]
To be honest, I'm not sure this is something many people would actually use. We try to keep the library slim, useful, and easy to maintain. There are likely better options than duplicating an existing method simply to add output buffering to it. Instead of modifying the library itself, why not obtain the raw image data one of these ways:

1. Wrap your output buffering around the existing `output()` method:

  ```php
  // Start output buffering
  ob_start();

  // Create and output the image the stdout
  $image = new SimpleImage();
  ...
  $image->output();
  
  // Grab the image data
  $image_data = ob_get_contents();

  // Stop output buffering
  ob_end_clean();
  ```

2. Write to a temp file using `save()` and then grab the data with `file_get_contents()`:

  ```php
  // Create and save the image to a file
  $image = new SimpleImage();
  ...
  $image->save($file);

  // Grab the image data
  $image_data = file_get_contents($file);
  ```

3. You might even be able to save it to `php://memory` and grab the data directly from memory (no temp file required)

Wouldn't it be better to use one of these options instead?

**Comment by lanaguanifw** [comment]
No, for our project it is the best option that I mentioned, but I understand his reasons, thanks anyway.

**Comment by terrylinooo** [comment]
```
  public function fromRaw($raw) {
    return $this->fromDataUri(base64_encode($raw));
  }
```


```
  public function toRaw($mimeType = null, $quality = 100) {
    return $this->generate($mimeType, $quality);
  }
```

Add those two methods solve anything.
None duplication of code, easier to maintain.

**Comment by claviska** [comment]
Heads up! `fromString()` and `toString()` were just added in 2ecb41f. 🎉

**Pull request closed without merging**
