### PR TITLE
#92 Multi color text and multi color stroke

### PR DESCRIPTION
**Pull request by mikedidomizio**
Works good but I found that the imagettfbbox doesn't consider spacing for the next letter.  Had to add an (optional) parameter to the text method called "letter_spacing" which will bump the x-position a little bit ahead so the letters aren't all crammed side by side.

### CODE REVIEW

**Comment by adaniello** [comment]
:+1:

**Comment by claviska** [comment]
This is a solid PR, thanks. Only thing I noticed is that the example outputs `butterfly-multi-color-text-with-stroke.jpg` in just one text color:

butterfly-multi-color-text-with-stroke

Otherwise, looks great :)

**Comment by mikedidomizio** [comment]
I think you pulled from a previous commit?  The filenames changed a few times but ended up here c2bc518c5905c7f2514e262ae452cbf5edeaac59.  Should be named like this:
 
`butterfly-text-with-stroke-multi-colored-text.jpg`
`butterfly-text-with-stroke-multi-colored-stroke.jpg`

The reason why I named them that is for ordering.  Goes something like this in the folder:
text, multi colored text, stroke, multi colored stroke

**Comment by mikedidomizio** [comment]
Had to commit a change.  PHP was throwing a warning in the background.

**Comment by claviska** [comment]
Yep, think I pulled the wrong commit. Works fine. Thanks for the PR!

**Pull request merged**
