### PR TITLE
Fix transparent in Gif image

### PR DESCRIPTION
**Pull request by peter279k**
- It fixes the issue #159 and issue #221  .

### CODE REVIEW

**Comment by claviska** [comment]
Thanks for tackling this :)

Can you separate the autoloading changes into another PR? It's been awhile for me, but I'm pretty sure it won't have any adverse effect on existing 3.x users, can you confirm this? I'd just like to split it into a separate issue so we can address it separately.

Thanks!

**Comment by peter279k** [comment]
I will separate that two PRs.

**Comment by peter279k** [comment]
After using ```3.3``` latest version, the rotated GIF background image still has the same issue.

**Comment by claviska** [comment]
> After using 3.3 latest version, the rotated GIF background image still has the same issue.

So the issue still exists?

**Comment by peter279k** [comment]
Yes, the issue is still existed.

**Comment by claviska** [comment]
Ok, thanks. I'm closing this PR then. If you find a fix feel free to submit an updated one!

**Comment by peter279k** [comment]
Does this PR keep concern?

**Comment by claviska** [comment]
Sorry, I got confused by the earlier thread and dropped the ball. I'll test this manually when I get back to work later this week. (We seriously need some automated test cases for this lib!)

**Pull request merged**
